project_ecom/core/urls.py
from django.urls import path
from core import views
from django.contrib.auth.views import LogoutView

# Para usar imagenes cargadas por el usuario
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'  # Esto define el namespace

urlpatterns = [
    path('', views.index, name='home'),
    path('aboutMe', views.aboutMe, name="aboutMe"), # aboutMe page
    path('profile', views.profile, name="profile"), # profile
    path('profile/update', views.profileUpdate, name="profileUpdate"), # profile Update
    path('profile/changePwd', views.ChangePwd.as_view(), name="changePwd"), # change password
    
    # AUTH ------------------------------------------
    path('register', views.register, name="register"), # Register page
    path('my-login', views.my_login, name="my-login"), # Login page
    path('user-logout', LogoutView.as_view(template_name='auth/logout.html'), name="user-logout"), # Logout page

    # PRODUCTS ------------------------------------------
    path('products/', views.products, name='products'),
    path('products/add', views.add_product, name='add_product'),  # ADMIN - Add new product
    path('products/update/<int:product_id>', views.update_product, name='update_product'), # ADMIN - Update product
    path('products/delete/<int:product_id>', views.delete_product, name='delete_product'), # ADMIN - Delete product
    
    # REQUESTS ------------------------------------------
    path('requests', views.requests, name='requests'), #  ADMIN - Read requests with status in progress
    path('requests_all', views.requests_all, name='requests_all'), # ADMIN - Read all requests
    path('requests/update/<int:pur_id>', views.update_purchase, name='update_purchase'), # ADMIN - Update requests status
    
    # CART ------------------------------------------
    path('cart', views.cart, name='cart'), # Read all carts by user
    path('cart/add', views.add_cart, name='add_cart'), # # Add new cart
    path('cart/add_product', views.add_product_to_cart, name='add_product_to_cart'), # Add product to cart
    path('cart/ready', views.cart_ready, name='cart_ready'), # Close cart, send request to bar

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Para usar imagenes cargadas por el usuario

project_ecom/mensajeria/urls.py
from django.urls import path
from mensajeria import views

# Para usar imagenes cargadas por el usuario
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mensajeria'  # Esto define el namespace

urlpatterns = [
    path('chat', views.chat, name='chat'),
       
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Para usar imagenes cargadas por el usuario

project_ecom/project_ecom/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('msg/', include('mensajeria.urls'))
]

urlpatterns += static(settings.STATIC_URL, documents_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, documents_root = settings.MEDIA_ROOT)

project_ecom/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    # picture = models.CharField(max_length=100, default="{% static 'images/no-image.png' %}")
    picture = models.ImageField(upload_to='products', null=True)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    stock = models.IntegerField(default=0)

    def __str__(self):
        return str(self.title)

class Items(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField(default=0)
    subtotal = models.FloatField(default=0)

    def __str__(self):
        return "ID " + str(self.product.id) + " x " + str(self.quantity) 

class Purchase(models.Model):

    STATUS_CHOICES = [
        ('Para cargar', 'Para cargar'),
        ('Pendiente de aprobacion', 'Pendiente de aprobacion'),
        ('Pagado', 'Pagado'),
        ('En preparacion', 'En preparacion'),
        ('Listo para retirar', 'Listo para retirar'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado')
    ]
    
    creation_date = models.DateTimeField(auto_now_add=True)
    products = models.ManyToManyField('Items', blank=True)
    total = models.FloatField(default=0)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='Para cargar')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, default=1)

    def __str__(self):
        return str(self.creation_date) + " x " + str(self.total) 


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    birthDate = models.DateField(null=True)

project_ecom/core/forms.py
from .models import Product, Purchase
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

# - Create a product -------------------------------------------------------------------
class CreateProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ['picture', 'title', 'description', 'price', 'stock']
        """ labels = {
            'picture': 'imagen',
            'title': 'Titulo',
            'description': 'Descripcion',
            'price': 'Precio ($)',
            'stock': 'stock',
        } """


# - Update a product -------------------------------------------------------------------
class UpdateProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'stock']



# - Update a purchase -------------------------------------------------------------------
class UpdatePurchaseForm(forms.ModelForm):
    
    class Meta:
        model = Purchase
        fields = ['status']

# Registro de usuario --------------------------
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contrasenia', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir contrasenia', widget=forms.PasswordInput)

    class Meta: # configuraciones de mi formulario
        model = User
        fields = ['username',
                  'email',
                  'password1',
                  'password2']
        help_texts = {'username': '',
                      'email': ''}




# Edicion de perfil --------------------------
class ProfileUpdateForm(UserChangeForm):
    password = None
    email = forms.EmailField(required=False)
    first_name = forms.CharField(label='Nombre', required=False)
    last_name = forms.CharField(label='Apellido', required=False)
    avatar = forms.ImageField(required=False)
    birthDate = forms.DateField(label='Fecha de nacimiento (YYYY-MM-DD)', required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'birthDate', 'avatar']

project_ecom/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CreateProductForm, UpdateProductForm, UpdatePurchaseForm, ProfileUpdateForm
from .models import Product, Purchase, Items, UserInfo
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.urls import reverse_lazy
#from django.contrib.auth.models import auth, authenticate

# ----------------------------------------------------------------------------------------------------
# LOGIN AND REGISTRATION
# ----------------------------------------------------------------------------------------------------

# Register a user ---------------------------------------------------------
def register(request):
    
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            #messages.success(request, "Account created successfully!")
            return redirect("core:my-login")
    context = {'form':form}
    return render(request, 'auth/register.html', context=context)

# Login a user -------------------------------------------------------------
def my_login(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.get_user()
            login(request, username)
            UserInfo.objects.get_or_create(user=username)
            return redirect('core:home')
            
    context = {'form':form}
    return render(request, 'auth/login.html', context=context)

# Perfil -------------------------------------------------------------
@login_required(login_url='core:my-login')
def profile(request):
    cart_opened = Purchase.objects.filter(user=request.user, status="Para cargar").exists()
    if cart_opened == True:
        cart = Purchase.objects.filter(user=request.user, status="Para cargar").first()
        prods_qty = cart.products.count()
    else:
        prods_qty=0
    context = {'prods_qty':prods_qty, 'cart_opened': cart_opened}
    return render(request, 'auth/profile.html', context=context)

# Editar perfil -------------------------------------------------------------
@login_required(login_url='core:my-login')
def profileUpdate(request):
    user_info = request.user.userinfo
    form = ProfileUpdateForm(initial={'avatar': user_info.avatar, 'birthDate': user_info.birthDate}, instance=request.user)
    if request.method == "POST":
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            if form.cleaned_data.get('avatar'):
                user_info.avatar = form.cleaned_data.get('avatar')
                user_info.save()
            if form.cleaned_data.get('birthDate'):
                user_info.birthDate = form.cleaned_data.get('birthDate')
                print(form.cleaned_data.get('birthDate'))
                user_info.save()
            form.save()
            return redirect('core:profile')
    context = {'form':form}
    return render(request, 'auth/profileUpdateForm.html', context=context)

# Cambiar contrasena -------------------------------------------------------------
class ChangePwd(LoginRequiredMixin, PasswordChangeView):
    template_name = 'auth/profileChangePwd.html'
    success_url = reverse_lazy('core:profile')

# ----------------------------------------------------------------------------------------------------
# VARIOS
# ----------------------------------------------------------------------------------------------------

def index(request):
    return render (request, 'core/index.html')

@login_required(login_url='core:my-login')
def aboutMe(request):
    return render (request, 'aboutMe.html')


# PRODUCTS --------------------------------------------------------------------------
@login_required(login_url='core:my-login')
def products(request):
    try:
        query = request.GET.get('query')  # Tomamos el parámetro de la URL
        if query:
            #all_products = Product.objects.filter(title__icontains=query)  # Filtrar por nombre
            all_products = Product.objects.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )
        else:
            all_products = Product.objects.all()  # Mostrar todos los productos si no hay búsqueda
        cart_opened = Purchase.objects.filter(user=request.user, status="Para cargar").exists()
        if cart_opened == True:
            cart = Purchase.objects.filter(user=request.user, status="Para cargar").first()
            prods_qty = cart.products.count()
        else:
            prods_qty=0
        context = {'products': all_products, 'prods_qty':prods_qty, 'cart_opened': cart_opened}
        return render(request, 'core/products.html', context=context)
        #return render(request, 'core/products.html')
    except:
        return render(request, 'core/index.html')

@login_required(login_url='core:my-login')
def add_product(request):
    try:
        cart_opened = Purchase.objects.filter(user=request.user, status="Para cargar").exists()
        if cart_opened == True:
            cart = Purchase.objects.filter(user=request.user, status="Para cargar").first()
            prods_qty = cart.products.count()
        else:
            prods_qty=0
        
        if request.method == "POST": # POST request
            form = CreateProductForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
            return redirect("core:products") # In case the url is written manually
        else: # GET request
            form = CreateProductForm()
            context = {'form': form, 'prods_qty':prods_qty, 'cart_opened': cart_opened}
            return render(request, 'core/add_product.html', context=context) # When clicking the ADD A NEW CLIENT button
    except:
        """ messages.error(request, "Error while trying to create a new customer. Please, contact admin.") """
        return redirect("core:products")


@login_required(login_url='core:my-login')
def update_product (request, product_id):
    try:
        product = Product.objects.get(id=product_id)
        if request.method == 'POST':
            form = UpdateProductForm(request.POST, instance=product)
            if form.is_valid():
                form.save()
            return redirect("core:products")
        form = UpdateProductForm(instance=product)
        context = {'form': form, 'product': product}
        return render(request, 'core/update_product.html', context=context)
        
    except:
        return redirect("core:products")
    
@login_required(login_url='core:my-login')
def delete_product (request, product_id):
    try:
        product = Product.objects.get(id=product_id)
        product.delete()
        return redirect("core:products")
        
    except:
        return redirect("core:products")


# REQUESTS --------------------------------------------------------------------------
@login_required(login_url='core:my-login')
def requests(request):
    try:
        if request.user.username == 'admin':
            purchases = Purchase.objects.filter(
                ~Q(status__in=['Para cargar', 'Finalizado', 'Cancelado'])
            )
            context = {'purchases': purchases}
            return render(request, 'core/requests.html', context=context)
        return redirect("core:products")
    except:
        return redirect("core:products")

@login_required(login_url='core:my-login')
def requests_all(request):
    try:
        if request.user.username == 'admin':
            purchases = Purchase.objects.exclude(status='Para cargar')
            context = {'purchases': purchases}
            return render(request, 'core/requests.html', context=context)
        return redirect("core:products")
    except:
        return redirect("core:products")

@login_required(login_url='core:my-login')
def update_purchase (request, pur_id):
    try:
        if request.user.username == 'admin':
            purchase = Purchase.objects.get(id=pur_id)
            if request.method == 'POST':
                form = UpdatePurchaseForm(request.POST, instance=purchase)
                if form.is_valid():
                    form.save()
                return redirect("core:requests")
            form = UpdatePurchaseForm(instance=purchase)
            context = {'form': form, 'product': purchase}
            return render(request, 'core/update_purchase.html', context=context)
        return redirect("core:requests")
    except:
        return redirect("core:requests")

# CART --------------------------------------------------------------------------
@login_required(login_url='core:my-login')
def cart(request):
    try:
        cart_opened = Purchase.objects.filter(user=request.user, status="Para cargar").exists()
        if cart_opened == True:
            cart = Purchase.objects.filter(user=request.user, status="Para cargar").first()
            prods_qty = cart.products.count()
        else:
            prods_qty=0
        all_carts = Purchase.objects.filter(user=request.user)
        context = {'carts': all_carts, 'prods_qty':prods_qty, 'cart_opened': cart_opened}
        return render(request, 'core/cart.html', context=context)
        #return render(request, 'core/products.html')
    except:
        return render(request, 'core/index.html')


@login_required(login_url='core:my-login')
def add_cart(request):
    try:
        # chequear que el ultimo po creado sea distinto de vacio
        all_carts = Purchase.objects.filter(user=request.user, status="Para cargar").exists()
        if all_carts == False:
            new_cart = Purchase()

project_ecom/templates/core/add_product.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<body class="bg-black">
    <div class="container shadow-md p-5 form-layout text-white">
        <h3> Nuevo producto </h3>
        <br>

        <form method="POST" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            
            <br>
            
            <button type="submit" class="btn btn-success">                
                Save &nbsp; <i class="fa fa-check" aria-hidden="true"></i>
            </button>

            &nbsp;

            <a href="{% url 'products' %}" class="btn btn-secondary"> 
                Return &nbsp; <i class="fa fa-arrow-left" aria-hidden="true"></i>
            </a>


        </form>

    </div>

    <br>

</body>

{% endblock %}

project_ecom/templates/core/navbar.html
{% load static %}


{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'core:home' %}"><img src="{% static 'images/logo2.png' %}" alt="" class="rounded mx-2" width="70px"></a>
      {% if user.is_authenticated %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% endif %}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}    
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'core:products' %}">Listado de productos</a>
            </li>

            {% if not user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'core:cart' %}">Mis pedidos</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'core:requests' %}">Pedidos</a>
            </li>
            {% endif %}

            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'core:aboutMe' %}">Acerca de mi</a>
            </li>
            {% endif %}
          {% else %}

          <li class="nav-item">
            <a href="{% url 'core:my-login' %}" class="nav-link">Login</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'core:register' %}" class="nav-link">Register</a>
          </li>
  
          {% endif %}

          
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'mensajeria:chat' %}">Chat</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:profile' %}">Perfil</a>
          </li>
          <li class="nav-item">
            <form action={% url 'core:user-logout' %} method="post">
              {% csrf_token %}
              <button class="nav-link">Signout</button>
            </form>
          </li>
          {% endif %}

        </ul>
        
        {% if not user.is_superuser %}
          {% if cart_opened %}
          <div class="mx-3">
            <a href="{% url 'core:cart' %}">
              <button type="button" class="btn btn-primary position-relative">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-dash" viewBox="0 0 16 16">
                  <path d="M6.5 7a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1z"/>
                  <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                </svg>
                Mi pedido
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                  {{prods_qty}}
                  <span class="visually-hidden">unread messages</span>
                </span>
              </button>
            </a>
          </div>
          {% endif %}
        {% endif %}
        {% if user.is_authenticated %}
        <img class="avatar avatar-xs mx-2" src="{{request.user.userinfo.avatar.url}}" alt="...">
        <span class="badge text-bg-secondary">{{request.user}}</span>
        {% endif%}



      </div>
    </div>
  </nav>

  {% endblock %}

project_ecom/templates/core/products.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<body class="bg-black">
    <h1 class="text-white text-center fw-lighter m-3">Listado de productos</h1>

    {% if user.is_superuser %}
    <br>
      <button type="button" class="btn btn-warning text-dark">
        <a class="text-dark" href="{% url 'core:add_product' %}">Agregar producto</a>
      </button>       
    <br>
      {% endif %}
    
    <form action="{% url 'core:products' %}" method="get">
      <input type="text" name="query" placeholder="Buscar productos..." value="{{ query|default:'' }}">
      <button type="submit">Buscar</button>
    </form>
    
    {% if products %}
    <div class="d-flex flex-wrap justify-content-around">
      {% for product in products %}
        
        <div class="card m-2" style="width: 18rem;">
          
          <img src="{{product.picture.url}}" class="card-img-top" alt="{{product.picture}}" style="width: 100%; height: 150px; object-fit: cover;">
          
          <div class="card-body">
            <h5 class="card-title">{{product.title}}</h5>
            <p class="card-text">{{product.description}}</p>
                  
            <div class="container-fluid text-center">
              <div class="row justify-content-center">
                      <div class="col">
                        <form action="{% url 'core:add_product_to_cart' %}" method="post">
                          {% csrf_token %}
                          {% if user.is_superuser %}
                          <div class="input-group">
                            <button type="button" class="btn btn-outline-dark bg-light">
                              <a href="{% url 'core:update_product' product.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                  <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                                </svg>
                              </a>
                            </button>
                            <button type="button" class="btn btn-outline-dark bg-light">
                              <a href="{% url 'core:delete_product' product.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                                </svg>
                              </a>
                            </button>
                          </div>
                          {% else %}
                          <div class="input-group">
                            <input type="hidden" name="product_id" value="{{ product.id }}">
                            <input type="number" class="form-control" id="qty_selected" name="qty_selected" value=0>
                            <button class="btn btn-outline-secondary" type="submit">+</button>
                          </div>
                          {% endif %}
                        </form>
                      </div>
                      <div class="col">
                        <span class="fst-italic mt-3">${{product.price}}</span>
                      </div>
              </div>
            </div> 
          </div>
        </div>
  
      {% endfor %}

    </div>

    {% else %}
    <p class="text-white">No se encontraron productos.</p>
    {% endif %}
          
 
    
</body>

{% endblock %}

project_ecom/templates/core/requests.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<body class="bg-black">
    <h1 class="text-white text-center fw-lighter m-3">Listado de pedidos</h1>
    <div class="input-group">
      <button type="button" class="btn btn-warning text-dark">
        <a class="text-dark" href="{% url 'core:requests' %}">En proceso</a>
      </button>
      &nbsp
      <button type="button" class="btn btn-warning text-dark">
        <a class="text-dark" href="{% url 'core:requests_all' %}">Todos</a>
      </button> 

    </div>
    <br>
    <div class="mx-5">
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col align-middle">Codigo</th>
                <th scope="col align-middle">Estado</th>
                <th scope="col align-middle">Usuario</th>
                <th scope="col align-middle">Creation date</th>
                <th scope="col align-middle">Productos</th>
                <th scope="col align-middle">Total</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for pur in purchases %}
                <tr>
                  <th scope="row" class="align-middle">{{pur.id}}</th>
                  <td class="align-middle">{{pur.status}}</td>
                  <td class="align-middle">{{pur.user}}</td>
                  <td class="align-middle">{{pur.creation_date}}</td>
                  
                  <td>
                    
                    <table class="table">
                      <thead>
                        <tr>
                          <th scope="col ">Producto</th>
                          <th scope="col">Valor individual</th>
                          <th scope="col">Cantidad</th>
                          <th scope="col">Subtotal</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for prod in pur.products.all %}
                          <tr>
                            <th scope="row">{{prod.product.title}}</th>
                            <td>${{prod.product.price}}</td>
                            <td>{{prod.quantity}}</td>
                            <td>${{prod.subtotal}}</td>
                          </tr> 
                        {% endfor %}

                      </tbody>
                    </table>
                  </td>

                  <td class="align-middle">${{pur.total}}</td>
                  <td class="align-middle text-center"> 
                    <button type="button" class="btn btn-outline-dark bg-light">
                      <a href="{% url 'core:update_purchase' pur.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                        </svg>
                      </a>
                    </button>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
</body>

{% endblock %}